# Generated by Django 6.0.3 on 2026-04-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_alter_categoria_options_categoria_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contapagar',
            options={'ordering': ['vencimento', 'grupo_referencia', 'parcela_numero', '-id']},
        ),
        migrations.AddField(
            model_name='contapagar',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='grupo_referencia',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='parcela_numero',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='parcelas_total',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
