# Generated by Django 5.1.3 on 2026-04-08 21:17

import django.db.models.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0004_alter_contapagar_options_contapagar_data_pagamento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name="categoria",
            constraint=models.UniqueConstraint(
                django.db.models.functions.Lower("nome"),
                condition=models.Q(parent__isnull=True),
                name="uniq_categoria_raiz_nome",
            ),
        ),
        migrations.AddConstraint(
            model_name="categoria",
            constraint=models.UniqueConstraint(
                django.db.models.functions.Lower("nome"),
                "parent",
                condition=models.Q(parent__isnull=False),
                name="uniq_subcategoria_nome_por_pai",
            ),
        ),
    ]
