# Generated by Django 5.1.3 on 2026-04-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0005_add_performance_indexes"),
        ("loja", "0005_alter_categoria_nome_and_more"),
    ]

    operations = []
